[
  "si ganteng",
  "si jelek",
  "anomali bt script",
  "kang hapus sumber",
  "kang ngocok",
  "Anomali maklu",
  "orang gila",
  "anak rajin",
  "anak cerdas",
  "lonte gurun",
  "dugong",
  "macan yatim",
  "buaya darat",
  "kanjut terbang",
  "kuda kayang",
  "janda salto",
  "lonte alas",
  "jembut singa",
  "gajah terbang",
  "kuda cacat",
  "jembut pink",
  "sabun bolong",
  "si yatim",
  "anak kuya",
  "kudanil"
]
